// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220110.5

#pragma once
#ifndef WINRT_Windows_Management_Update_Cluster_1_H
#define WINRT_Windows_Management_Update_Cluster_1_H
#include "winrt/impl/Windows.Management.Update.Cluster.0.h"
WINRT_EXPORT namespace winrt::Windows::Management::Update::Cluster
{
    struct __declspec(empty_bases) IAcquireEnvironmentInfoResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAcquireEnvironmentInfoResult>
    {
        IAcquireEnvironmentInfoResult(std::nullptr_t = nullptr) noexcept {}
        IAcquireEnvironmentInfoResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAcquireEnvironmentInfoResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAcquireEnvironmentInfoResultFactory>
    {
        IAcquireEnvironmentInfoResultFactory(std::nullptr_t = nullptr) noexcept {}
        IAcquireEnvironmentInfoResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAreRebootsPendingResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAreRebootsPendingResult>
    {
        IAreRebootsPendingResult(std::nullptr_t = nullptr) noexcept {}
        IAreRebootsPendingResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IAreRebootsPendingResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IAreRebootsPendingResultFactory>
    {
        IAreRebootsPendingResultFactory(std::nullptr_t = nullptr) noexcept {}
        IAreRebootsPendingResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClusterNativeEnvironmentOperations :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClusterNativeEnvironmentOperations>
    {
        IClusterNativeEnvironmentOperations(std::nullptr_t = nullptr) noexcept {}
        IClusterNativeEnvironmentOperations(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClusterNativeEnvironmentOperationsPlugin :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClusterNativeEnvironmentOperationsPlugin>
    {
        IClusterNativeEnvironmentOperationsPlugin(std::nullptr_t = nullptr) noexcept {}
        IClusterNativeEnvironmentOperationsPlugin(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClusterNativeNodeOperations :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClusterNativeNodeOperations>
    {
        IClusterNativeNodeOperations(std::nullptr_t = nullptr) noexcept {}
        IClusterNativeNodeOperations(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClusterNativeNodeOperationsPlugin :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClusterNativeNodeOperationsPlugin>
    {
        IClusterNativeNodeOperationsPlugin(std::nullptr_t = nullptr) noexcept {}
        IClusterNativeNodeOperationsPlugin(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClusterUpdateServices :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IClusterUpdateServices>
    {
        IClusterUpdateServices(std::nullptr_t = nullptr) noexcept {}
        IClusterUpdateServices(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInstallUpdateTaskResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInstallUpdateTaskResult>
    {
        IInstallUpdateTaskResult(std::nullptr_t = nullptr) noexcept {}
        IInstallUpdateTaskResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IInstallUpdateTaskResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IInstallUpdateTaskResultFactory>
    {
        IInstallUpdateTaskResultFactory(std::nullptr_t = nullptr) noexcept {}
        IInstallUpdateTaskResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRollbackUpdateTaskResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRollbackUpdateTaskResult>
    {
        IRollbackUpdateTaskResult(std::nullptr_t = nullptr) noexcept {}
        IRollbackUpdateTaskResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IRollbackUpdateTaskResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IRollbackUpdateTaskResultFactory>
    {
        IRollbackUpdateTaskResultFactory(std::nullptr_t = nullptr) noexcept {}
        IRollbackUpdateTaskResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScanUpdateTaskResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IScanUpdateTaskResult>
    {
        IScanUpdateTaskResult(std::nullptr_t = nullptr) noexcept {}
        IScanUpdateTaskResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IScanUpdateTaskResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IScanUpdateTaskResultFactory>
    {
        IScanUpdateTaskResultFactory(std::nullptr_t = nullptr) noexcept {}
        IScanUpdateTaskResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IStageUpdateTaskResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IStageUpdateTaskResult>
    {
        IStageUpdateTaskResult(std::nullptr_t = nullptr) noexcept {}
        IStageUpdateTaskResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IStageUpdateTaskResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IStageUpdateTaskResultFactory>
    {
        IStageUpdateTaskResultFactory(std::nullptr_t = nullptr) noexcept {}
        IStageUpdateTaskResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateCredential :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateCredential>
    {
        IUpdateCredential(std::nullptr_t = nullptr) noexcept {}
        IUpdateCredential(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateCredentialFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateCredentialFactory>
    {
        IUpdateCredentialFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateCredentialFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateInstallRecord :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateInstallRecord>
    {
        IUpdateInstallRecord(std::nullptr_t = nullptr) noexcept {}
        IUpdateInstallRecord(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateInstallRecordFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateInstallRecordFactory>
    {
        IUpdateInstallRecordFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateInstallRecordFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateInstaller :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateInstaller>
    {
        IUpdateInstaller(std::nullptr_t = nullptr) noexcept {}
        IUpdateInstaller(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateInstallerPlugin :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateInstallerPlugin>
    {
        IUpdateInstallerPlugin(std::nullptr_t = nullptr) noexcept {}
        IUpdateInstallerPlugin(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateOperationResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateOperationResult>
    {
        IUpdateOperationResult(std::nullptr_t = nullptr) noexcept {}
        IUpdateOperationResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateOperationResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateOperationResultFactory>
    {
        IUpdateOperationResultFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateOperationResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdatePendingOperationResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdatePendingOperationResult>
    {
        IUpdatePendingOperationResult(std::nullptr_t = nullptr) noexcept {}
        IUpdatePendingOperationResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdatePendingOperationResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdatePendingOperationResultFactory>
    {
        IUpdatePendingOperationResultFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdatePendingOperationResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdatePluginVersionInfo :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdatePluginVersionInfo>
    {
        IUpdatePluginVersionInfo(std::nullptr_t = nullptr) noexcept {}
        IUpdatePluginVersionInfo(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdatePluginVersionInfoFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdatePluginVersionInfoFactory>
    {
        IUpdatePluginVersionInfoFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdatePluginVersionInfoFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateRecipeNodeValidationInfoRecord :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateRecipeNodeValidationInfoRecord>
    {
        IUpdateRecipeNodeValidationInfoRecord(std::nullptr_t = nullptr) noexcept {}
        IUpdateRecipeNodeValidationInfoRecord(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateRecipeNodeValidationInfoRecordFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateRecipeNodeValidationInfoRecordFactory>
    {
        IUpdateRecipeNodeValidationInfoRecordFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateRecipeNodeValidationInfoRecordFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateScanRecord :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateScanRecord>
    {
        IUpdateScanRecord(std::nullptr_t = nullptr) noexcept {}
        IUpdateScanRecord(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateScanRecordFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateScanRecordFactory>
    {
        IUpdateScanRecordFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateScanRecordFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateStageRecord :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateStageRecord>
    {
        IUpdateStageRecord(std::nullptr_t = nullptr) noexcept {}
        IUpdateStageRecord(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateStageRecordFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateStageRecordFactory>
    {
        IUpdateStageRecordFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateStageRecordFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateTaskResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateTaskResult>
    {
        IUpdateTaskResult(std::nullptr_t = nullptr) noexcept {}
        IUpdateTaskResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateTaskResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateTaskResultFactory>
    {
        IUpdateTaskResultFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateTaskResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateValidationLogMessage :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateValidationLogMessage>
    {
        IUpdateValidationLogMessage(std::nullptr_t = nullptr) noexcept {}
        IUpdateValidationLogMessage(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUpdateValidationLogMessageFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IUpdateValidationLogMessageFactory>
    {
        IUpdateValidationLogMessageFactory(std::nullptr_t = nullptr) noexcept {}
        IUpdateValidationLogMessageFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IValidateAllNodesUpdateRecipeResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IValidateAllNodesUpdateRecipeResult>
    {
        IValidateAllNodesUpdateRecipeResult(std::nullptr_t = nullptr) noexcept {}
        IValidateAllNodesUpdateRecipeResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IValidateAllNodesUpdateRecipeResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IValidateAllNodesUpdateRecipeResultFactory>
    {
        IValidateAllNodesUpdateRecipeResultFactory(std::nullptr_t = nullptr) noexcept {}
        IValidateAllNodesUpdateRecipeResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IValidateClusterEnvironmentResult :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IValidateClusterEnvironmentResult>
    {
        IValidateClusterEnvironmentResult(std::nullptr_t = nullptr) noexcept {}
        IValidateClusterEnvironmentResult(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IValidateClusterEnvironmentResultFactory :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IValidateClusterEnvironmentResultFactory>
    {
        IValidateClusterEnvironmentResultFactory(std::nullptr_t = nullptr) noexcept {}
        IValidateClusterEnvironmentResultFactory(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
